title: CS2 Nade Guide
description: A simple site built with Jekyll
url: "https://zwaleo.github.io"  # Change this to your GitHub Pages URL
baseurl: ""  # Leave empty for root or change for subpath (e.g. "/blog")
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
