site_name: CS2 Nades and Tactics
site_url: https://zwaleo.github.io
nav:
  - Home: index.md
  - Mirage: mirage.md
theme:
  palette:
    primary: "amber"
    accent: "amber"
    scheme: "slate"
  name: material

  markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption